# Generated by Django 4.0 on 2021-12-14 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('genre_game', '0002_question_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='question',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_question', to='genre_game.question'),
        ),
        migrations.AlterField(
            model_name='game',
            name='answer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='submitted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submited_user', to='auth.user'),
        ),
    ]
