# Generated by Django 4.0 on 2021-12-15 05:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('genre_game', '0003_game_question_alter_game_answer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='is_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='game',
            name='won',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='genreteam',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='game_genre', to='genre_game.genre'),
        ),
    ]
