# Generated by Django 4.0 on 2021-12-15 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre_game', '0005_game_round'),
    ]

    operations = [
        migrations.AddField(
            model_name='genreteam',
            name='sort_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
