# Generated by Django 4.0 on 2021-12-16 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre_game', '0006_genreteam_sort_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='genreteam',
            name='questions_answered',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddField(
            model_name='genreteam',
            name='questions_attempted',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
