# Generated by Django 4.0 on 2021-12-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('genre_game', '0008_game_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
